Knjiznica.Presentation/Controllers/MembersController.cs
using Knjiznica.Core.Models.Models;
using Knjiznica.Core.Models.ViewModels;
using Knjiznica.Core.Services;
using Knjiznica.Core.Services.Commands.Members;
using Knjiznica.Core.Services.Commands.Rents;
using Knjiznica.Core.Services.Queries.Members;
using Knjiznica.Core.Services.Queries.Rents;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using X.PagedList;
using X.PagedList.Mvc.Core;
using static System.Reflection.Metadata.BlobBuilder;


namespace Knjiznica.Presentation.Controllers
{
    public class MembersController : Controller
    {
        readonly ICommandHandler<EditMemberCommand> _editMember;
        readonly ICommandHandler<AddMemberCommand> _addMember;
        readonly ICommandHandler<DeleteMemberCommand> _deleteMember;
        readonly IQueryHandler<GetMembersQuery, IQueryable<Member>> _getMembers;
        readonly IQueryHandler<GetMemberByIdQuery, Member> _getMemberById;
        readonly IQueryHandler<GetRentsWithMemberIdQuery, IQueryable<Rent>> _getResntsWithMemberId;
        public MembersController(
            ICommandHandler<EditMemberCommand> editMember,
            ICommandHandler<AddMemberCommand> addMember,
            ICommandHandler<DeleteMemberCommand> deleteMember,
            IQueryHandler<GetMembersQuery, IQueryable<Member>> getMembers,
            IQueryHandler<GetMemberByIdQuery, Member> getMembersById,
            IQueryHandler<GetRentsWithMemberIdQuery, IQueryable<Rent>> getResntsWithMemberId)
        {
            _editMember = editMember;
            _addMember = addMember;
            _deleteMember = deleteMember;
            _getMemberById = getMembersById;
            _getMembers = getMembers;
            _getResntsWithMemberId = getResntsWithMemberId;
        }
        public async Task<IActionResult> Index( int page)
        {
            var members = await _getMembers.HandleAsync(new GetMembersQuery());
            ViewData["Page"] = page;
            int take = 3;
            int pageNo = (int)Math.Ceiling((decimal)members.Count() / take);
            ViewData["MaxPage"] = pageNo - 1;

            return View(members.Skip(page * take).Take(take));
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind()] Member member)
        {
            if (ModelState.IsValid)
            {
                await _addMember.HandleAsync(new AddMemberCommand(member));
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }
        public async Task<IActionResult> MembersRents(int id)
        {
            
            var membersRents = await _getResntsWithMemberId.HandleAsync(new GetRentsWithMemberIdQuery(id));

            var rentViewModels = (from kc in membersRents
                                  .Include(x=>x.Member)
                                  .Include(x=>x.Book)
                                  select new RentViewModel()
                                  {
                                      RentId = kc.RentId,
                                      BookId = kc.BookId,
                                      MemberId = kc.RentId,
                                      MemberName = kc.Member.Name,
                                      BookTitle = kc.Book.Title,
                                      DateRented = kc.DateRented,
                                  });
            var Name = await _getMemberById.HandleAsync(new GetMemberByIdQuery(id));
            ViewData["Name"] = Name.Name;
            return View(rentViewModels);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var member = await _getMemberById.HandleAsync(new GetMemberByIdQuery(id));

            return View(member);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind()] Member member)
        {
            if (ModelState.IsValid)
            {
                await _editMember.HandleAsync(new EditMemberCommand(member));
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        public async Task<IActionResult> Delete(int id)
        {
            var member = await _getMemberById.HandleAsync(new GetMemberByIdQuery(id));

            return View(member);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            var member = await _getMemberById.HandleAsync(new GetMemberByIdQuery(id));
            await _deleteMember.HandleAsync(new DeleteMemberCommand(member));

            return RedirectToAction(nameof(Index));
        }




    }
}

Knjiznica.Presentation/Controllers/RentsController.cs
using Knjiznica.Core.Models;
using Knjiznica.Core.Models.EditModels;
using Knjiznica.Core.Models.Models;
using Knjiznica.Core.Models.ViewModels;
using Knjiznica.Core.Services.Commands.Books;
using Knjiznica.Core.Services;
using Knjiznica.Core.Services.Commands.Rents;
using Knjiznica.Core.Services.Queries.Authors;
using Knjiznica.Core.Services.Queries.Books;
using Knjiznica.Core.Services.Queries.Members;
using Knjiznica.Core.Services.Queries.Rents;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using X.PagedList.Mvc.Core;
using X.PagedList;
using Knjiznica.Core.Services.Queries.Genres;
using Microsoft.AspNetCore.Mvc.Rendering;
using static System.Reflection.Metadata.BlobBuilder;

namespace Knjiznica.Presentation.Controllers
{
    public class RentsController : Controller
    {
        ////private readonly MediatR.IMediator _mediator;
        readonly ICommandHandler<DeleteRentCommand> _deleteRent;
        readonly ICommandHandler<AddRentCommand> _addRent;
        readonly ICommandHandler<EditRentCommand> _editRent;
        readonly IQueryHandler<GetRentsQuery, IQueryable<Rent>> _getRents;
        readonly IQueryHandler<GetRentByIdQuery, Rent> _getRentById;
        readonly IQueryHandler<GetRentsWithBookIdQuery, IQueryable<Rent>> _getRentsWithBookId;
        readonly IQueryHandler<GetRentsWithMemberIdQuery, IQueryable<Rent>> _getRentsWithMemberId;
        readonly IQueryHandler<GetMembersQuery, IQueryable<Member>> _getMembers;
        readonly IQueryHandler<GetBooksQuery, IQueryable<Book>> _getBooks;
        public RentsController(ICommandHandler<DeleteRentCommand> deleteRent,
            ICommandHandler<AddRentCommand> addRent,
            ICommandHandler<EditRentCommand> editRent,
            IQueryHandler<GetRentsQuery, IQueryable<Rent>> getRents,
            IQueryHandler<GetRentByIdQuery, Rent> getRentById,
            IQueryHandler<GetRentsWithBookIdQuery, IQueryable<Rent>> getRentsWithBookId,
            IQueryHandler<GetRentsWithMemberIdQuery, IQueryable<Rent>> getRentsWithMemberId,
            IQueryHandler<GetMembersQuery, IQueryable<Member>> getMembers,
            IQueryHandler<GetBooksQuery, IQueryable<Book>> getBooks)
        {
            _deleteRent = deleteRent;
            _addRent = addRent;
            _editRent = editRent;
            _getRents = getRents;
            _getRentById = getRentById;
            _getRentsWithBookId = getRentsWithBookId;
            _getRentsWithMemberId = getRentsWithMemberId;
            _getMembers = getMembers;
            _getBooks = getBooks;
        }


        // GET: Rents
        public async Task<IActionResult> Index(string sortOrder, string searchTitle, string searchMember, int page)
        {
            ViewData["IsLate"] = String.IsNullOrEmpty(sortOrder) ? "true" : "";
            ViewData["DateSortParam"] = sortOrder == "date" ? "dateDesc" : "date";
            ViewData["MemberFilter"] = searchMember;
            ViewData["TitleFilter"] = searchTitle;

            var rents = await _getRents.HandleAsync(new GetRentsQuery());

            var rentViewModels = (from kc in rents
                              .Include(x => x.Member)
                              .Include(x => x.Book)
                              select new RentViewModel()
                              {
                                  RentId = kc.RentId,
                                  BookId = kc.BookId,
                                  MemberId = kc.RentId,
                                  MemberName = kc.Member.Name,
                                  BookTitle = kc.Book.Title,
                                  DateRented = kc.DateRented,
                              });
            if (!String.IsNullOrEmpty(searchTitle))
            {
                rentViewModels = rentViewModels.Where(x => x.BookTitle.Contains(searchTitle));
            }
            if (!String.IsNullOrEmpty(searchMember))
            {
                rentViewModels = rentViewModels.Where(x => x.MemberName.Contains(searchMember));
            }

            ViewData["Page"] = page;
            int take = 3;
            int pageNo = (int)Math.Ceiling((decimal)rents.Count() / take);
            ViewData["MaxPage"] = pageNo - 1;

            switch (sortOrder)
            {
                case "date":
                    rentViewModels = rentViewModels.OrderBy(x => x.DateRented);
                    break;
                case "dateDesc":
                    rentViewModels = rentViewModels.OrderByDescending(x => x.DateRented);
                    break;
                case "true":
                    rentViewModels = rentViewModels.Where(x => x.DateRented.AddDays(Constants.MAX_RENT_DAYS) < DateTime.Today);
                    break;
            }

            return View(rentViewModels.ToList().Skip(page * take).Take(take));
        }

        public async Task<IActionResult> Create()
        {
            var books = await _getBooks.HandleAsync(new GetBooksQuery());
            var members = await _getMembers.HandleAsync(new GetMembersQuery());


            ViewData["book"] = new SelectList(books, "BookId", "Title");
            ViewData["member"] = new SelectList(members, "MemberId", "Name");


            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind()] Rent rent)
        {
            var books = await _getBooks.HandleAsync(new GetBooksQuery());
            var members = await _getMembers.HandleAsync(new GetMembersQuery());
            ViewData["BookId"] = new SelectList(books, "BookId", "BookId", rent.BookId);
            ViewData["MemberId"] = new SelectList(members, "MemberId", "MemberId", rent.RentId);
            if (ModelState.IsValid)
            {
                await _addRent.HandleAsync(new AddRentCommand(rent));
                return RedirectToAction(nameof(Index));
            }
            return View(rent);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var rent = await _getRentById.HandleAsync(new GetRentByIdQuery(id));
            var members = await _getMembers.HandleAsync(new GetMembersQuery());
            var books = await _getBooks.HandleAsync(new GetBooksQuery());

            RentEM rentEM = new RentEM()
            {
                MemberName = members.Where(x=>x.MemberId == rent.MemberId).Single().Name,
                BookTitle = books.Where(x=>x.BookId == rent.BookId).Single().Title,
                BookId = rent.BookId,
                MemberId = rent.MemberId,
                RentId = rent.RentId,
                DateRented = rent.DateRented,
                IsLate = rent.IsLate,
                Members = members.ToDictionary(x => x.MemberId, x => x.Name),
                Books = books.ToDictionary(x => x.BookId, x => x.Title)

            };

            return View(rentEM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind()] Rent rent)
        {
            if (ModelState.IsValid)
            {
                await _editRent.HandleAsync(new EditRentCommand(rent));
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public async Task<IActionResult> Delete(int id)
        {
            var rent = await _getRentById.HandleAsync(new GetRentByIdQuery(id));
            var members = await _getMembers.HandleAsync(new GetMembersQuery());
            var books = await _getBooks.HandleAsync(new GetBooksQuery());

            RentViewModel rentVM = new RentViewModel()
            {
                RentId = rent.RentId,
                BookId = rent.BookId,
                MemberId = rent.RentId,
                MemberName = members.Where(x => x.MemberId == rent.MemberId).Single().Name,
                BookTitle = books.Where(x => x.BookId == rent.BookId).Single().Title,
                DateRented = rent.DateRented,

            };

            return View(rentVM);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            var rent = await _getRentById.HandleAsync(new GetRentByIdQuery(id));

            
            await _deleteRent.HandleAsync(new DeleteRentCommand(rent));

            return RedirectToAction(nameof(Index));
        }

    }
}

Knjiznica.Presentation/Views/Members/Create.cshtml
@model Knjiznica.Core.Models.Models.Member

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Member</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Knjiznica.Presentation/Views/Members/Delete.cshtml
@model Knjiznica.Core.Models.Models.Member

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="MemberId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Knjiznica.Presentation/Views/Members/Details.cshtml
@model Knjiznica.Core.Models.Models.Member

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Member</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.MemberId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Knjiznica.Presentation/Views/Members/Edit.cshtml
@model Knjiznica.Core.Models.Models.Member

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Member</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MemberId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Knjiznica.Presentation/Views/Members/Index.cshtml
@model IEnumerable<Knjiznica.Core.Models.Models.Member>

@{
    ViewData["Title"] = "Index";
}

<h1>Members</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="MembersRents" asp-route-id="@item.MemberId">
                        @Html.DisplayFor(modelItem => item.Name)
                    </a>
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.MemberId">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.MemberId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
@if (ViewBag.Page > 0)
{
    <a href="@Url.Action("Index", new { page = ViewBag.Page - 1 })" 
       class="btn btn-default">
        &laquo; Prev
    </a>
}
@if (ViewBag.Page < ViewBag.MaxPage)
{
    <a href="@Url.Action("Index", new { page = ViewBag.Page + 1 })" 
       class="btn btn-default">
        Next &raquo;
    </a>
}

Knjiznica.Presentation/Views/Members/MembersRents.cshtml
@model IEnumerable<Knjiznica.Core.Models.ViewModels.RentViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Rents by @ViewData["Name"]</h1>
<p>
    <a asp-action="Create">Create New</a>
</p>
<a asp-action="Index" class="btn btn-primary"> Back to full list</a>
<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["DateSortParam"]">
                    @Html.DisplayNameFor(model => model.DateRented)
                </a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["IsLate"]">
                    @Html.DisplayNameFor(model => model.IsLate)
                </a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookTitle)
                <form asp-action="Index" method="get" asp-route-seachString="@ViewData["TitleFilter"]">
                    <p>
                        <input type="text" name="searchTitle" value="@ViewData["TitleFilter"]" />
                    </p>
                </form>
            </th>         
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DateRented)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsLate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BookTitle)
                </td>
                <td>
                    <a asp-controller="Rents" asp-action="Edit" asp-route-id="@item.RentId">Edit</a> |
                    <a asp-controller="Rents" asp-action="Delete" asp-route-id="@item.RentId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>